
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/


spring:
  application:
    name: service-feign
  main:
    allow-bean-definition-overriding: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1


  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8093
feign:
  hystrix:
    enabled: true




